version: '3.7'

services:
  redis:
    container_name: my_redis
    image: redis:5.0.5-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
       - ./data/redis:/data
